a_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('apps.a_home.urls')),
    path('profile/', include('apps.a_account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/a_account/urls.py
from django.urls import path
from apps.a_account import views

app_name = 'a_account' 

urlpatterns = [
    path('', views.profile_view, name='profile-view'),
    path('@<username>', views.profile_view, name='profile'),
    path('edit/', views.profile_edit_view, name='profile-edit-view'),
    path('deactivate/', views.profile_active_view, name='profile-deactivate-view'),
    path('activate/', views.profile_active_view, name='profile-activate-view'),
    path('onboarding/', views.profile_edit_view, name='profile-onboarding'),
    path('settings/', views.profile_settings_view, name='profile-settings'),
    path('emailchange/', views.profile_settings_view, name='profile-emailchange'),
    path('username/edit/', views.profile_settings_view, name='profile-username-edit'),
    path('emailverify/', views.profile_email_verify, name='profile-emailverify'),
]

apps/a_account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.templatetags.static import static


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='avatars/', null=True, blank=True)
    displayname = models.CharField(max_length=25, null=True, blank=True)
    info = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True, help_text="Designates whether this user is active.")
    
    def __str__(self):
        return str(self.user)
    
    @property
    def name(self):
        if self.displayname:
            name = self.displayname
        else:
            name = self.user.username
        return name
    
    @property
    def avatar(self):
        try:
            avatar = self.image.url
        except:
            avatar = static('images/avatar.svg')
        return avatar

apps/a_account/forms.py
from django import forms
from apps.a_account.models import Profile
from django.contrib.auth.models import User
import re

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user', 'is_active']
        widgets = {
            'image': forms.FileInput(attrs={'class':'cursor-pointer w-full overflow-clip rounded-radius border border-outline bg-surface-alt/50 text-sm text-on-surface file:mr-4 file:border-none file:bg-surface-alt file:px-4 file:py-2 file:font-medium file:text-on-surface-strong focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary disabled:cursor-not-allowed disabled:opacity-75 dark:border-outline-dark dark:bg-surface-dark-alt/50 dark:text-on-surface-dark dark:file:bg-surface-dark-alt dark:file:text-on-surface-dark-strong dark:focus-visible:outline-primary-dark'}),
            'displayname': forms.TextInput(attrs={'placeholder': 'Add display name...'}),
            'info': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Add information'})
        }

class EmailForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ['email']
        
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exclude(id=self.instance.id).exists():
            raise forms.ValidationError(f'Email {email} is not available')
        pattern = r'^[a-zA-Z0-9]+@[a-zA-Z0-9.]+$'

        if not re.match(pattern, email):
            raise forms.ValidationError(
                "Email must contain only letters and digits, with a single '@' symbol."
            )
        return email
        
class UsernameForm(forms.ModelForm):
    username = forms.CharField(required=True)
    class Meta:
        model = User
        fields = ['username']
        
    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exclude(id=self.instance.id).exists():
            raise forms.ValidationError(f'Username @{username} is not available')
        if not re.match(r'^\w+$', username):
            raise forms.ValidationError('Username can only contain letters, digits, and underscores.')
        return username

apps/a_account/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from apps.a_account.forms import ProfileForm, EmailForm, UsernameForm
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib import messages
from allauth.account.utils import send_email_confirmation
from django.contrib.auth import logout
from apps.a_account.models  import Profile


@login_required
def profile_view(request, username=None):
    if username:
        profile = get_object_or_404(User, username=username).profile
    else:
        profile = request.user.profile
        # try:
        #     profile = request.user.profile
        # except:
        #     return redirect('account_login')
    return render(request, 'a_account/profile.html', {'profile':profile})


@login_required
def profile_edit_view(request):
    form = ProfileForm(instance=request.user.profile)
    
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('a_account:profile-view')
        
    if request.path == reverse('a_account:profile-onboarding'):
        onboarding = True
    else:
        onboarding = False
    
    context = {
        'form':form,
        'onboarding':onboarding,
    }
    return render(request, 'a_account/profile_edit.html', context)

@login_required
def profile_settings_view(request):
    if request.path == reverse('a_account:profile-emailchange'):
        if request.htmx:
            form = EmailForm(instance=request.user)
            return render(request, 'partials/email_form.html', {'form':form})
        
        if request.method == 'POST':
            form = EmailForm(request.POST, instance=request.user)
            if form.is_valid():
                form.save()
                # then signal updates email address and set verified to false on the all auth table
                # then send confirmation email
                send_email_confirmation(request, request.user)
                return redirect('a_account:profile-settings')
            else:
                return render(request, 'a_account/profile_settings.html', {'email_form':form})
        else:
            return redirect('home')
        
    if request.path == reverse('a_account:profile-username-edit'):
        if request.htmx:
            form = UsernameForm(instance=request.user)
            return render(request, 'partials/username_form.html', {'form':form})
        
        if request.method == 'POST':
            form = UsernameForm(request.POST, instance=request.user)
            if form.is_valid():
                form.save()
                return redirect('a_account:profile-settings')
            else:
                return render(request, 'a_account/profile_settings.html', {'username_form':form})
        else:
            return redirect('home')
        
    return render(request, 'a_account/profile_settings.html')


@login_required
def profile_email_verify(request):
    send_email_confirmation(request, request.user)
    return redirect('a_account:profile-settings')


@login_required
def profile_active_view(request):
    profile = get_object_or_404(Profile, pk=request.user.id)
    if request.path == reverse('a_account:profile-deactivate-view'):
        if request.method == 'POST':
            logout(request)
            profile.is_active = False
            profile.save()
            messages.success(request, 'Account deactivated')
            return redirect('home')
        else:
            return render(request, 'a_account/profile_deactivate.html')
        
    if request.path == reverse('a_account:profile-activate-view'):
        if profile.is_active:
            return redirect('home')
        if request.method == 'POST':
            profile.is_active = True
            profile.save()
            messages.success(request, 'Account reactivated')
            return redirect('home')
        else:
            return render(request, 'a_account/profile_activate.html')

apps/a_account/templates/a_account/profile.html
{% extends 'layouts/blank.html' %}

{% block content %}
<div class="max-w-lg mx-auto flex flex-col items-center pt-20 px-4 bg-theme-bg">
    <img class="w-36 h-36 rounded-full object-cover mb-4" src="{{ profile.avatar }}" />
    <div class="text-center">
        <h1 class="text-on-surface">{{ profile.name }}</h1>
        <div class="text-on-surface 400 mb-2 mt-3">@{{ profile.user.username }}</div>
        {% if profile.info %}
        <div class="mt-8 text-on-surface">{{ profile.info|linebreaksbr }}</div>
        {% endif %}  
    </div>
</div>

{% endblock %}

apps/a_account/templates/a_account/profile_activate.html
{% extends 'layouts/box.html' %}

{% block content %}

<h1>Your account is deactivated</h1>
<p>Are you sure you want to reactivate your account?</p>

<form method='POST'>
    {% csrf_token %}
    <button type="submit" class="cursor-pointer whitespace-nowrap rounded-radius bg-danger border border-danger px-4 py-2 text-sm font-medium tracking-wide text-on-danger transition hover:opacity-75 text-center focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-danger active:opacity-100 active:outline-offset-0 disabled:opacity-75 disabled:cursor-not-allowed dark:bg-danger dark:border-danger dark:text-on-danger dark:focus-visible:outline-danger">Yes, I want to reactivate my account</button>
    <a class="whitespace-nowrap rounded-radius bg-secondary border border-secondary px-4 py-2 text-sm font-medium tracking-wide text-on-secondary transition hover:opacity-75 text-center focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-secondary active:opacity-100 active:outline-offset-0 disabled:opacity-75 disabled:cursor-not-allowed dark:bg-secondary-dark dark:border-secondary-dark dark:text-on-secondary-dark dark:focus-visible:outline-secondary-dark" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
</form>

{% endblock %}

apps/a_account/templates/a_account/profile_deactivate.html
{% extends 'layouts/box.html' %}

{% block content %}

<h1 class="text-on-surface">Delete Account</h1>
<p class="text-on-surface">Are you sure you want to deactivate your account?</p>

<form method='POST'>
    {% csrf_token %}
    <button type="submit" class="cursor-pointer whitespace-nowrap rounded-radius bg-danger border border-danger px-4 py-2 text-sm font-medium tracking-wide text-on-danger transition hover:opacity-75 text-center focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-danger active:opacity-100 active:outline-offset-0 disabled:opacity-75 disabled:cursor-not-allowed dark:bg-danger dark:border-danger dark:text-on-danger dark:focus-visible:outline-danger">Yes, I want to deactivate my account</button>
    <a class="whitespace-nowrap rounded-radius bg-secondary border border-secondary px-4 py-2 text-sm font-medium tracking-wide text-on-secondary transition hover:opacity-75 text-center focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-secondary active:opacity-100 active:outline-offset-0 disabled:opacity-75 disabled:cursor-not-allowed dark:bg-secondary-dark dark:border-secondary-dark dark:text-on-secondary-dark dark:focus-visible:outline-secondary-dark" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
</form>

{% endblock %}

apps/a_account/templates/a_account/profile_edit.html
{% extends 'layouts/box.html' %}

{% block content %}
{% if onboarding %}
    <h1 class="mb-4 text-on-surface">Complete your Profile</h1>
{% else %}
    <h1 class="mb-4 text-on-surface">Edit your Profile</h1>
{% endif %}

<div class="text-center flex flex-col items-center">
    <img id="avatar" class="w-36 h-36 rounded-full object-cover my-4" src="{{ user.profile.avatar }}" />
    <div class="text-center max-w-md ">
        <h1 id="displayname" class="text-on-surface">{{ user.profile.displayname|default:"" }}</h1>
        <div class="mb-2 -mt-3 text-on-surface">@{{ user.username }}</div>
    </div>
</div>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}<p class="[&_input]:bg-amber-700">{{ field }}</p>{% endfor %}
    <!-- {{ form.as_p }} -->
    <button type="submit" class="whitespace-nowrap rounded-radius bg-primary border border-primary px-4 py-2 text-sm font-medium tracking-wide text-on-primary transition hover:opacity-75 text-center focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary active:opacity-100 active:outline-offset-0 disabled:opacity-75 disabled:cursor-not-allowed dark:bg-primary-dark dark:border-primary-dark dark:text-on-primary-dark dark:focus-visible:outline-primary-dark" >Submit</button>
    {% if onboarding %}
    <a class="whitespace-nowrap bg-transparent rounded-radius border border-primary px-4 py-2 text-sm font-medium tracking-wide text-primary transition hover:opacity-75 text-center focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary active:opacity-100 active:outline-offset-0 disabled:opacity-75 disabled:cursor-not-allowed dark:border-primary-dark dark:text-primary-dark dark:focus-visible:outline-primary-dark" href="{% url 'home' %}">Skip</a>
    {% else %}
    <a class="whitespace-nowrap bg-transparent rounded-radius border border-primary px-4 py-2 text-sm font-medium tracking-wide text-primary transition hover:opacity-75 text-center focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary active:opacity-100 active:outline-offset-0 disabled:opacity-75 disabled:cursor-not-allowed dark:border-primary-dark dark:text-primary-dark dark:focus-visible:outline-primary-dark" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
    {% endif %}
</form>

{% endblock %}

apps/a_account/templates/a_account/profile_settings.html
{% extends 'layouts/box.html' %}

{% block content %}

<h1 class="mb-8 text-on-surface">Account Settings</h1>

<table class="w-full text-sm text-left text-gray-500">
    <tbody>
        {% comment %} {% if form_error %}
        {{form_error}}
        {% endif %} {% endcomment %}
        {% if email_form.errors %}
            <ul class="errorlist">
                {% for field_errors in email_form.errors.values %}
                    {% for error in field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        {% elif username_form.errors %}
            <ul class="errorlist">
                {% for field_errors in username_form.errors.values %}
                    {% for error in field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        {% endif %}
        <tr class="border-b">
        {% if username_form %}
            <th scope="row" class="pt-4 pb-4 text-base font-bold text-on-surface">
                Username
            </th>
            <td id="username" class="pt-4 pb-4 px-6">
                <form action="{% url 'a_account:profile-username-edit' %}" method="post" class="flex gap-2 text-black" autocomplete="off">
                    {% csrf_token %}
                    {% for field in username_form %}{{ field }}{% endfor %}
                    <button class="block whitespace-nowrap rounded-radius bg-primary border border-primary px-4 py-2 text-sm font-medium tracking-wide text-on-primary transition hover:opacity-75 text-center focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary active:opacity-100 active:outline-offset-0 disabled:opacity-75 disabled:cursor-not-allowed dark:bg-primary-dark dark:border-primary-dark dark:text-on-primary-dark dark:focus-visible:outline-primary-dark" type="submit">Submit</button>
                </form>
            </td>
            <td class="pt-4 pb-5 px-6">
                <a href="{% url 'a_account:profile-settings' %}" class="font-medium text-blue-600 hover:underline">
                    Cancel
                </a>
            </td>
        {% else %}
            <th scope="row" class="pt-4 pb-4 text-base font-bold text-on-surface">
                Username
            </th>
            <td id="username" class="pt-4 pb-4 px-6">
                {{ user.username }}
            </td>
            <td class="pt-4 pb-5 px-6">
                <a id="username-edit" 
                    class="font-medium text-blue-600 hover:underline cursor-pointer"
                    hx-get="{% url 'a_account:profile-username-edit' %}"
                    hx-target="#username"
                    hx-swap="innerHTML"
                >
                    Edit
                </a>
            </td>
        {% endif %}
        </tr>
        
        <tr {% if email_form %} class="border-b" {% endif %}>
        {% if email_form %}
            <th scope="row" class="pt-4 pb-1 text-base font-bold text-on-surface">
                Email address
            </th>
            <td id="email-address" class="pt-4 pb-1 px-6">
                <form action="{% url 'a_account:profile-emailchange' %}" method="post" class="flex gap-2 text-black" autocomplete="off">
                    {% csrf_token %}
                    {% for field in email_form %}{{ field }}{% endfor %}
                    <button class="block whitespace-nowrap rounded-radius bg-primary border border-primary px-4 py-2 text-sm font-medium tracking-wide text-on-primary transition hover:opacity-75 text-center focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary active:opacity-100 active:outline-offset-0 disabled:opacity-75 disabled:cursor-not-allowed dark:bg-primary-dark dark:border-primary-dark dark:text-on-primary-dark dark:focus-visible:outline-primary-dark" type="submit">Submit</button>
                </form>
            </td>
            <td class="pt-4 pb-1 px-6">
                <a href="{% url 'a_account:profile-settings' %}" class="font-medium text-blue-600 hover:underline">
                    Cancel
                </a>
            </td>
        {% else %}
        
            <th scope="row" class="pt-4 pb-1 text-base font-bold text-on-surface">
                Email address
            </th>
            <td id="email-address" class="pt-4 pb-1 px-6">
                {% if user.email %}{{ user.email }}{% else %}No Email{% endif %}
            </td>
            <td class="pt-4 pb-1 px-6">
                <a id="email-edit" 
                    class="font-medium text-blue-600 hover:underline cursor-pointer"
                    hx-get="{% url 'a_account:profile-emailchange' %}"
                    hx-target="#email-address"
                    hx-swap="innerHTML"
                >
                    Edit
                </a>
            </td>
        </tr>
        <tr class="border-b">
            <th scope="row" class="pb-4 font-medium text-gray-900">  
            </th>
            <td class="px-6 pb-4">
                {% if user.emailaddress_set.first.verified %}
                <span class="text-green-500">Verified</span>{% else %}
                <span class="text-amber-500">Not verified</span>
                {% endif %}
            </td>
            <td class="px-6 pb-4">
                <a href="{% url 'a_account:profile-emailverify' %}" class="font-medium text-blue-600 hover:underline">
                    {% if not user.emailaddress_set.first.verified %}Verify{% endif %}
                </a>
            </td>
        </tr>
        {% endif %}
        <tr class="border-b">
            <th scope="row" class="py-4 text-base font-bold text-on-surface">
                Deactivate Account
            </th>
            <td class="px-6 py-4">
                Once deactivated, you can no longer access the site unless reactivated.
            </td>
            <td class="px-6 py-4">
                <a href="{% url 'a_account:profile-deactivate-view' %}" class="font-medium text-red-600 hover:underline">
                    Deactivate
                </a>
            </td>
        </tr>
    </tbody>
</table>


{% endblock %}